language: go
go:
  - 1.11.x
script:
  - make
before_deploy:
  - make VERSION=${TRAVIS_TAG} pakage -j2
deploy:
  provider: releases
  api_key: $API_KEY
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
